# Generated by Django 4.2 on 2023-04-28 13:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.PathAndRename('/media')),
        ),
    ]
